name: CI - DevSecOps

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # üîê DEPENDENCY SECURITY (SCA)
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "nodejs-frontend"
          path: "."
          format: "HTML"
          out: "reports"

      # üîê CODE SECURITY (SAST)
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # üü• SECURITY GATE (BLOCK PIPELINE)
      - name: Sonar Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # üê≥ BUILD IMAGE
      - name: Docker Build
        run: |
          docker build -t 861550625988.dkr.ecr.ap-south-1.amazonaws.com/nodejs-frontend:${{ github.sha }} .

      # üîê IMAGE SECURITY
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 861550625988.dkr.ecr.ap-south-1.amazonaws.com/nodejs-frontend:${{ github.sha }}
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

      # ‚òÅÔ∏è PUSH ONLY IF SECURE
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-south-1 \
          | docker login --username AWS --password-stdin 861550625988.dkr.ecr.ap-south-1.amazonaws.com

      - name: Push Image
        run: |
          docker push 861550625988.dkr.ecr.ap-south-1.amazonaws.com/nodejs-frontend:${{ github.sha }}

